Add check against Python 2.X.
Before:

    $ python2.7 maxproduct
      File "maxproduct", line 3
    SyntaxError: Non-ASCII character '\xc2' in file maxproduct on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python2.7 maxproduct
      File "maxproduct", line 11
        ...  # Python 3.X is required
        ^
    SyntaxError: invalid syntax